### ISSUE TITLE
autopep8 incorrectly skips sources as standard library files

### ISSUE THREAD

**Issue by nputikhin** [microsoft/vscode-autopep8#125]
Symptoms: Trying to format a source with autopep8 v2023.6.0 doesn't do anything. The code is on a Debian-based system.

Output>autopep8:
```
2023-07-13 12:20:40.266 [info] [Trace - 12:20:40 PM] Sending request 'textDocument/formatting - (3)'.
2023-07-13 12:20:40.268 [info] [Trace - 12:20:40 PM] Received notification 'window/logMessage'.
2023-07-13 12:20:40.268 [info] [Warn  - 12:20:40 PM] Skipping standard library file: /usr/local/home/username/code/foo.py
2023-07-13 12:20:40.269 [info] [Trace - 12:20:40 PM] Received response 'textDocument/formatting - (3)' in 2ms.
```

Likely culprit is #103 - `_site_paths` were changed to include paths from `sysconfig`
https://github.com/microsoft/vscode-autopep8/blob/96c1d850cd3a0ef3ca302a518861cd077d64be1c/bundled/tool/lsp_utils.py#L32-L39

These paths are then used as prefixes to detect standard library files.
https://github.com/microsoft/vscode-autopep8/blob/96c1d850cd3a0ef3ca302a518861cd077d64be1c/bundled/tool/lsp_utils.py#L57-L60

These files are skipped here:
https://github.com/microsoft/vscode-autopep8/blob/96c1d850cd3a0ef3ca302a518861cd077d64be1c/bundled/tool/lsp_server.py#L349-L351

Output from python:
```
Python 3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_default_scheme()
'posix_local'
>>> sysconfig.get_paths()
{'stdlib': '/usr/lib/python3.11', 'platstdlib': '/usr/lib/python3.11', 'purelib': '/usr/local/lib/python3.11/dist-packages', 'platlib': 
'/usr/local/lib/python3.11/dist-packages', 'include': '/usr/include/python3.11', 'platinclude': '/usr/include/python3.11', 'scripts': 
'/usr/local/bin', 'data': '/usr/local'} 
```

`'data' : '/usr/local'` is a directory for data files ([doc](https://docs.python.org/3/library/sysconfig.html#installation-paths)), but here it is also a base folder for the user's home folder. So the source file, which in our example is `/usr/local/home/username/code/foo.py`, gets skipped. I believe `data` shouldn't be added to `_site_paths`.

**Comment by karthiknadig** [comment]
Can you try build `2023.7.11941910` and let me know if it works?

![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/1f40e836-d5c5-4c0a-b98a-527b26fb7ecf)

**Comment by nputikhin** [comment]
Just checked, can confirm that it works now. Thanks for fixing it so quickly!
