### ISSUE TITLE
The problem of reporting errors on argparse example

### ISSUE THREAD

**Issue by Debianov** [microsoft/vscode-autopep8#140]
Recently, my annoying mistake in the autopep8 config took place
```json
	...
	"autopep8.args": ["--global-config, ./config.lake8"]
```
instead
```json
	...
	"autopep8.args": ["--global-config", "./config.lake8"]
```
There was error in the vscode logs (command pallete > show logs > autopep8) under the `info` level
`2023-08-05 02:46:32.475 [info] cannot mix stdin and regular files`. 
The text of the error is sent, apparently, [along with a class](https://github.com/hhatto/autopep8/blob/5b9110ba53fecd60cd3091fb66d808e8ced3b2e8/autopep8.py#L3851) whose name says a lot more about my situation. It seems to me that it is worth changing something in the output of errors and in determining their level.

**Comment by karthiknadig** [comment]
I will investigate and see if we can expose this issue better.
