### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by radu-ion** [microsoft/vscode-autopep8#145]
Configuration:
Version: 1.81.1 (system setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Python 3.11.4
autopep8 version v2023.6.0

Problem:
![autopep8-not-working](https://github.com/microsoft/vscode-autopep8/assets/18706300/2ff3774e-d5f0-40a2-8e7f-4d9c7802f521)

Settings:
"editor.defaultFormatter": "ms-python.autopep8"

**Comment by karthiknadig** [comment]
@radu-ion IT looks like you have selected the code to format. That is not supported yet. Please use the format document command instead.

**Comment by radu-ion** [comment]
The 'Format Document' option works. My bad, closing the issue.
