### ISSUE TITLE
Add a warning when formatting is skipped for user

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-autopep8#155]

**Comment by luabud** [comment]
We are reserving this issue for Grace Hopper's Open Source Day, which will take place on September 22nd, 2023. If you're part of the event and would like to submit a contribution to this issue, please let us know, and we'll be happy to assign it to you.

For other community members who are not participating in the event, we appreciate your interest in contributing! We kindly request that you wait until after September 22nd to work on this issue. If no one from the event has been assigned to it by then, we'll gladly assign it to you. Thank you for your understanding and support!

**Comment by emmeline2** [comment]
I would like to work on this PR!

**Comment by emmeline2** [comment]
Hi @karthiknadig, 

I am trying to work on this pr but I am getting this error when doing the setup steps. Have you seen it before? I do have the right version of python I think. 
![image](https://github.com/microsoft/vscode-autopep8/assets/24498010/3e395efc-d94a-4d6b-b269-d105d29145cf)

**Comment by karthiknadig** [comment]
@emmeline2 you can run `nox --list` to see the list of commands. I suspect the command name is wrong.
