### ISSUE TITLE
Support format on range

### ISSUE THREAD

**Issue by RainEggplant** [microsoft/vscode-autopep8#16]
When I try to format selected code with this extension, it prompts:

> Extension 'autopep8' is configured as formatter but it cannot format 'Python'-files

But `autopep8` actually supports formatting a code fragment, and the Python extension with `autopep8` can work properly.

**Comment by Apreche** [comment]
I am experiencing the same issue.

**Comment by sangorrin** [comment]
"editor.formatOnSaveMode": "modifications" would be appreciated too :)

**Comment by fasavard** [comment]
Glad to know I'm not alone. Or at least a message that says it is not supported would be helpful

**Comment by MarcelFox** [comment]
Same issue here:

![image](https://github.com/microsoft/vscode-autopep8/assets/4885041/ea40afd7-15ec-48e2-b73b-dc3a4078e959)

![image](https://github.com/microsoft/vscode-autopep8/assets/4885041/281e5a31-30ea-4f05-96d2-60317cc3b7ba)

**Comment by bpkroth** [comment]
Just another +1 ...

**Comment by alexandrosandre** [comment]
And another one

**Comment by badger117jm** [comment]
I have this issue as well.  It's frustrating since I want to format the code that I've added or modified not the whole file as it would introduce changes to the project that are not related to the scope of my issue.

**Comment by dmorgoon** [comment]
+1

**Comment by stakaz** [comment]
Same for me, as far as I remember it worked when autopep8 was part of the python extension. Or am I wrong?

**Comment by karthiknadig** [comment]
> Same for me, as far as I remember it worked when autopep8 was part of the python extension. Or am I wrong?

Python extension did not support formatting on range. It formatted the entire document. I think people are running into this because of the shortcut. There are two shortcuts:
![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/cfc91ec3-aa73-4f63-b6d2-11a6d6b1df3e)

This extension supports the `editor.action.formatDocument` and the actual range formatting is something that we are open to take PR on.

**Comment by Pyrestone** [comment]
I think this is mis-tagged as a "feature request".

Not supporting the formatSelection is a massive regression from the bundled and now deprecated autopep8 functionality in vscode-python, which now refers to this repo as a replacement.

Please consider adding this to your roadmap.

**Comment by karthiknadig** [comment]
@Pyrestone I plan on adding this support this milestone. I need to fix an issue with how we generate the edits currently to support this, but intent is to add this support along with the edit fix.

**Comment by karthiknadig** [comment]
PR for this is up. Still in draft. If some one wants to give it a try here is the build:
https://github.com/microsoft/vscode-autopep8/suites/16845625991/artifacts/962135968
