### ISSUE TITLE
Capitalize instances of "python" in user-facing text 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-autopep8#160]
Whenever there are user facing references like in settings, commands or descriptions, we should capitalize "Python".

**Comment by luabud** [comment]
We are reserving this issue for Grace Hopper's Open Source Day, which will take place on September 22nd, 2023. If you're part of the event and would like to submit a contribution to this issue, please let us know, and we'll be happy to assign it to you.

For other community members who are not participating in the event, we appreciate your interest in contributing! We kindly request that you wait until after September 22nd to work on this issue. If no one from the event has been assigned to it by then, we'll gladly assign it to you. Thank you for your understanding and support!

**Comment by vinitaparasrampuria** [comment]
Can you please take up this issue?

**Comment by hyndavi17** [comment]
Can I please take up this?

**Comment by aarushinair** [comment]
Could I please be assigned to this issue?

**Comment by luabud** [comment]
@hyndavi17 @aarushinair I assigned @vinitaparasrampuria since she commented first, but you could either collaborate or find another issue!

**Comment by hyndavi17** [comment]
@vinitaparasrampuria is it possible to collaborate?

**Comment by vinitaparasrampuria** [comment]
@hyndavi17 yeah sure! I have started working on it. You are welcome to join!

**Comment by amandaguan-ag** [comment]
I am GHC OSD participant. I would like to work on this issue. Can you please assign me.
