### ISSUE TITLE
Message: KeyError: <function continued_indentation at 0x7f79d4bdc700>   Code: -32602 

### ISSUE THREAD

**Issue by panxin801** [microsoft/vscode-autopep8#168]
Hello, I use vscode on MacOS with  vscode version:
 版本: 1.82.0 (Universal)
提交: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
日期: 2023-09-06T22:09:41.364Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 21.6.0

it coming out the following error:
2023-09-26 23:35:06.586 [info] [Error - 23:35:06] Request textDocument/formatting failed.
2023-09-26 23:35:06.586 [info]   Message: KeyError: <function continued_indentation at 0x7f79d4bdc700>
  Code: -32602 
{'traceback': ['  File "/Users/edy/.vscode/extensions/ms-python.autopep8-2023.6.0/bundled/libs/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/Users/edy/.vscode/extensions/ms-python.autopep8-2023.6.0/bundled/libs/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n', '  File "/Users/edy/.vscode/extensions/ms-python.autopep8-2023.6.0/bundled/tool/lsp_server.py", line 73, in formatting\n    edits = _formatting_helper(document)\n', '  File "/Users/edy/.vscode/extensions/ms-python.autopep8-2023.6.0/bundled/tool/lsp_server.py", line 93, in _formatting_helper\n    result = _run_tool_on_document(document, use_stdin=True)\n', '  File "/Users/edy/.vscode/extensions/ms-python.autopep8-2023.6.0/bundled/tool/lsp_server.py", line 429, in _run_tool_on_document\n    result = utils.run_module(\n', '  File "/Users/edy/.vscode/extensions/ms-python.autopep8-2023.6.0/bundled/tool/lsp_utils.py", line 153, in run_module\n    return _run_module(module, argv, use_stdin, source)\n', '  File "/Users/edy/.vscode/extensions/ms-python.autopep8-2023.6.0/bundled/tool/lsp_utils.py", line 138, in _run_module\n    runpy.run_module(module, run_name="__main__")\n', '  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 210, in run_module\n    return _run_code(code, {}, init_globals, run_name, mod_spec)\n', '  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n', '  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/autopep8.py", line 414, in <module>\n    del pycodestyle._checks[\'logical_line\'][pycodestyle.continued_indentation]\n']}

can you help me with this? thank you

**Comment by karthiknadig** [comment]
@panxin801 Please try the pre-release this is fixed there.
