### ISSUE TITLE
Running 'autopep8' Formatter running forever

### ISSUE THREAD

**Issue by cezarmezzalira** [microsoft/vscode-autopep8#178]
Today I stated a single project with Python 3.12.0 and when I save a file, a message saying: "Running 'autopep8' Formatter".

The only way to end the process is by kill it through terminal.

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:45:31.402Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-34-generic

Extension autopep8 version: v2023.6.0

![image](https://github.com/microsoft/vscode-autopep8/assets/20330507/33dcaf8f-3330-468a-b788-4de3b88d0bef)
****

**Comment by karthiknadig** [comment]
@cezarmezzalira Please try the pre-release version of the extension. It is updated to work with 3.12. Give it a try and let us know.

**Comment by cezarmezzalira** [comment]
@karthiknadig works fine with pre-release version.

When the fixes will be released?

Thanks!

**Comment by karthiknadig** [comment]
@cezarmezzalira This will likely be published to stable next week.

**Comment by cezarmezzalira** [comment]
Ok, thanks for your help!
