### ISSUE TITLE
Tabs are being expanded regardless of project configuration

### ISSUE THREAD

**Issue by diogoeichert** [microsoft/vscode-autopep8#180]
From the document itself:

> Tabs or Spaces?
> Spaces are the _preferred_ indentation method.
> Tabs should be used solely to **remain consistent with code that is already indented with tabs**.

Source: https://pep8.org/#tabs-or-spaces

The current behavior is expanding all tabs to spaces, regardless of the project configuration (VS Code tabs configuration, settings.json, EditorConfig, etc.)

This should not happen, the extension should respect the existing indentation settings.

**Comment by karthiknadig** [comment]
@diogoeichert We don't actually do anything in this extension to specifically change tab to spaces. This extension just launches autopep8 on the contents of the your file using `stdin` mode for autipep8.

You can set the following `"autopep8.trace.server": "verbose"` (this is a private setting so the IDE will mark it as unknown), in your User settings and open Output >autopep8. Then trigger formatting from a file with tabs. you can see the exact code that will be sent to autopep8 and what is returned from autopep8.

What we do is, take the unsaved string from the file buffer from the editor, pass it to autopep8, and return the changes back to IDE. The following is equivalent CLI command

Linux/Mac: 
```
cat <file path> | python -m autopep8 -
```
Windows:
```
cat <file path> | python -m autopep8 -
```

**Comment by diogoeichert** [comment]
Thanks, @karthiknadig. I've done some more tests after a clean VS Code install and could no longer reproduce the issue. Sorry for the mistaken report, closing it now.

**Comment by diogoeichert** [comment]
The problem happens after VS Code is restarted, since installing the extension doesn't immediately have an effect on the code. I'll do more tests as you've recommended.

**Comment by diogoeichert** [comment]
This is the content of `settings.json`:
```json
{
	"workbench.colorTheme": "Default Light+",
	"update.showReleaseNotes": false,
	"editor.minimap.enabled": false,
	"window.zoomLevel": 1,
	"workbench.startupEditor": "none",
	"svelte.enable-ts-plugin": true,
	"git.autofetch": true,
	"git.confirmSync": false,
	"git.enableSmartCommit": true,
	"explorer.confirmDelete": false,
	"diffEditor.ignoreTrimWhitespace": false,
	"editor.formatOnPaste": true,
	"editor.formatOnSave": true,
	"editor.formatOnType": true,
	"editor.defaultFormatter": "ms-python.autopep8",
	"[python]": {
		"editor.defaultFormatter": "ms-python.autopep8"
	},
	"editor.indentSize": "tabSize",
	"editor.detectIndentation": false,
	"editor.insertSpaces": false
}
```

And `cat <file path> | python -m autopep8 - > output.py` will produce a file with tabs expanded as spaces.

**Comment by karthiknadig** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
