### ISSUE TITLE
Extension 'autopep8' is configured as formatter but it cannot format 'Pyton'-files

### ISSUE THREAD

**Issue by Rawalanche** [microsoft/vscode-autopep8#182]
![image](https://github.com/microsoft/vscode-autopep8/assets/38806207/e295b560-f0cc-4159-80bd-458343c86d75)
I have latest stable version of the autopep8 extension.

I have configured it exactly as requested:
```
"[python]": {
    "editor.defaultFormatter": "ms-python.autopep8"
},
```
![image](https://github.com/microsoft/vscode-autopep8/assets/38806207/cd530fc0-1cd5-48c7-8332-b40c383bb6e5)

There is no "python.formatting.provider" set anywhere. Not in user nor in workspace/folder settings.

I don't have autopep8 python package installed, so I expect the extension is using its own.

The formatting does not work, whatsoever. When trying to format manually using "Format Selection" command, I get this error:
![image](https://github.com/microsoft/vscode-autopep8/assets/38806207/5e6070df-92fe-4856-8ba8-5ea9c10a7504)

The selection popup doesn't list autopep8 as available for formatting Python files:
![image](https://github.com/microsoft/vscode-autopep8/assets/38806207/e8a974ee-2eed-4725-82f3-1bc696b9f7ce)

Windows 11 22H2
VSCode 1.83.1
autopep8 v2023.6.0
Happens both with global environment as well as virtual environment.

Here's the log:
[autopep8.log](https://github.com/microsoft/vscode-autopep8/files/13070019/autopep8.log)

**Comment by karthiknadig** [comment]
This is fixed pre-release please give it a try.

Note that this happens when you try to format with selection. You should be able to still format whole documents using the "formatt Document " command.

**Comment by man2machine** [comment]
I am still getting this issue currently
