### ISSUE TITLE
Semicolon in f-string becomes newline

### ISSUE THREAD

**Issue by mpartel** [microsoft/vscode-autopep8#183]
```python
x = 3
print(f'lol; {x}')
```

gets autoformatted to

```python
x = 3
print(f'lol
{x}')
```

Same with double-quoted f-strings.

**Comment by mpartel** [comment]
This does not happen when running `autopep8` 2.0.4 on the command line, even with 0-5 `--aggressive` flags.

**Comment by karthiknadig** [comment]
@mpartel Can you set `"autoepe8.trace.server": "verbose"` in your user settings and attempt to format? This should generated detailed logs on Output >autopep8. Please share that log.

**Comment by karthiknadig** [comment]
I tried running this locally, it seems to be formatting it as expected (this is from logs after setting `"autoepe8.trace.server": "verbose"`)
```
2023-10-25 08:53:56.566 [info] file:///c%3A/GIT/scratch/autopep_test/sample.py :
****************************************************************************************************
x = 3
print(f'lol; {x}')

****************************************************************************************************

2023-10-25 08:53:56.567 [info] [Trace - 8:53:56 AM] Received response 'textDocument/formatting - (2)' in 230ms.
2023-10-25 08:53:56.567 [info] Result: [
    {
        "range": {
            "start": {
                "line": 2,
                "character": 0
            },
            "end": {
                "line": 2,
                "character": 0
            }
        },
        "newText": "\r\n"
    }
]

```

**Comment by mpartel** [comment]
Ah, this only happens if I have Python 3.12.0 (installed via pyenv) selected as the interpreter in VSCode. With 3.11.6 it works correctly.

Here's the log:
[autopep8-trace.log](https://github.com/microsoft/vscode-autopep8/files/13169853/autopep8-trace.log)

3.12.0 exhibits other f-string weirdness too, e.g.
`print(f'lol:')` becomes
`print(f'lol: ')`

**Comment by karthiknadig** [comment]
@mpartel This seems to be a bug on `autopep8` itself: https://github.com/hhatto/autopep8/issues/712
