### ISSUE TITLE
Command 'Format Document With...' resulted in an error

### ISSUE THREAD

**Issue by DePasqualeOrg** [microsoft/vscode-autopep8#184]
When I select "Format document with..." and autopep8 from the command palette, I get a dialog box with the following error:

Command 'Format Document With...' resulted in an error
KeyError: <function continued_indentation at 0x10a0a0e00>

These are my user settings for Python:

```
    "python.defaultInterpreterPath": "/usr/local/bin/python3",
    "[python]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2,
        "editor.formatOnType": true,
        "editor.defaultFormatter": "ms-python.autopep8",
    },
```

**Comment by karthiknadig** [comment]
This is fixed in pre-release. Please try the pre-release version of the extension.
