### ISSUE TITLE
It can work, but there are some doubts.

### ISSUE THREAD

**Issue by gakkiyomi** [microsoft/vscode-autopep8#202]
env:
   python 3.11.6
   vscode 1.84.2
   settings
   
![截屏2023-11-27 20 06 16](https://github.com/microsoft/vscode-autopep8/assets/41406557/9010b712-0174-4a73-9a01-ff01a9b7ba89)
![截屏2023-11-27 20 06 41](https://github.com/microsoft/vscode-autopep8/assets/41406557/3f2c7c4c-4e93-48f8-be30-b2cff5e5f333)

It can be formatted, but not extensively. Why can't this type of code be formatted?

  
    @abstractmethod
    def exec(self, api: FishPi, *args: Tuple[str, ...]):
        self.login(str, api, *args[0])
    def login(self, api: FishPi, mfa_code: str):
            if len(api.api_key) == 0:
            api.login(GLOBAL_CONFIG.auth_config.username,
                      GLOBAL_CONFIG.auth_config.password, mfa_code)

If there are syntax errors in the code, such as improper indentation, the plugin may not be able to format it?

https://github.com/microsoft/vscode-autopep8/assets/41406557/08fbcb6a-1532-4598-a065-d254811d2d16

**Comment by karthiknadig** [comment]
@gakkiyomi This extension is a wrapper for `autopep8` it doesn't really control its features or behavior. You will need to ask this on https://github.com/hhatto/autopep8
