### ISSUE TITLE
what is the "Unknown Configuration Setting"?

### ISSUE THREAD

**Issue by yaya159456** [microsoft/vscode-autopep8#214]
when i use the configs:
![1702955566469](https://github.com/microsoft/vscode-autopep8/assets/44463912/4b342ecd-014f-41ca-94b1-197d5aaed980)

it get the error! and it is unusefully

**Comment by yaya159456** [comment]
![image](https://github.com/microsoft/vscode-autopep8/assets/44463912/4d35a0e9-e72a-46b9-8d7d-1a8ea212ceb2)

**Comment by karthiknadig** [comment]
`python.formatting.provider` is not a valid setting, please remove it. `autopep.args` need not be put inside `[python]`.

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.

**Comment by bagustris** [comment]
It may be related to #256. Please open it @karthiknadig again.

**Comment by karthiknadig** [comment]
@bagustris it is not. You are using `autopep8` with setting by that don’t work when it is used on unsaved file buffers. I have left an explanation there.
