### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by KasperZutterman** [microsoft/vscode-autopep8#250]
Hi maintainers,

What are the requirement for making a new official release?
I would like to benefit from the changes already made to the $env expansion in [this PR](https://github.com/microsoft/vscode-autopep8/pull/223/files#diff-3a5b47a3d2e56af22ee3eeb11a7ac02b69ac7b6bf52f9b48a870acd00da9f39a), however this is not yet included in the latest release ([2023.8.0](https://github.com/microsoft/vscode-autopep8/releases/tag/v2023.8.0)).

Could you consider making a new release including these enhancements?
Thanks in advance.

**Comment by karthiknadig** [comment]
The fix should be in pre-release version  2023.9.10681010. We typically make releases after couple of weeks of feedback on fixes and stability of the pre-release versions.
