### ISSUE TITLE
使用字符串格式化时代码格式错误导致功能异常

### ISSUE THREAD

**Issue by mattholy** [microsoft/vscode-autopep8#267]
## Diagnostic Data
- Python version (& distribution if applicable, e.g., Anaconda): Python3.12.3
- Type of virtual environment used (e.g., conda, venv, virtualenv, etc.): None
- Operating system (and version): Windows 11
- Version of tool extension you are using: v2024.0.0

### Expected Behavior
我的原始代码为
```python
step_note = issue.notes.create({'body': f'balblalbalblablalbalblabll:\n- {"[x]" if has_reviewer else "[ ]"} balbalblalbalbalblalbalblba\n- [ ] blalbalbalblalalbalblalbalblal'})

```

### Actual Behavior
经过Autopep8自动格式化之后会变成：
```python
step_note = issue.notes.create({'body': f'balblalbalblablalbalblabll:\n- {
                               "[x]" if has_reviewer else "[ ]"} balbalblalbalbalblalbalblba\n- [ ] blalbalbalblalalbalblalbalblal'})
```
显然破坏了代码。
## Reproduction Steps:
1.在任意python文件中输入以下代码：
```python
step_note = issue.notes.create({'body': f'balblalbalblablalbalblabll:\n- {"[x]" if has_reviewer else "[ ]"} balbalblalbalbalblalbalblba\n- [ ] blalbalbalblalalbalblalbalblal'})
```
2.使用VS Code的Autopep8插件格式化代码

## Logs:

<details>
  <summary>Click here for detailed logs</summary>
  
</details>

## Outcome When Attempting Debugging Steps:

Did running it from the command line work?

**Comment by karthiknadig** [comment]
@mattholy I am not able to repo this locally. Can you please confirm the version of `autopep8` you are using? This does not seem to happen if you are using `autopep8==2.1.0`. You should be able to see the output here:
![image](https://github.com/microsoft/vscode-autopep8/assets/3840081/dd3e9ddf-fc41-4272-8752-49e2eece7d9d)

Please share the logs from that location (Output > autopep8)

**Comment by mattholy** [comment]
Before formatting:
![image](https://github.com/microsoft/vscode-autopep8/assets/22177897/5166ca19-973d-4f14-b395-603f8cd9e3d5)
After formatting:
![image](https://github.com/microsoft/vscode-autopep8/assets/22177897/a69a848b-381c-4450-9701-d7ad96e931f5)
The logs:
```log
2024-05-16 12:44:06.037 [info] [Trace - 12:44:06] Sending request 'textDocument/formatting - (6)'.
2024-05-16 12:44:06.042 [info] [Trace - 12:44:06] Received notification 'window/logMessage'.
2024-05-16 12:44:06.042 [info] C:\Users\smile\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m autopep8 -
2024-05-16 12:44:06.043 [info] [Trace - 12:44:06] Received notification 'window/logMessage'.
2024-05-16 12:44:06.043 [info] CWD Server: C:\Users\smile
2024-05-16 12:44:06.193 [info] [Trace - 12:44:06] Received response 'textDocument/formatting - (6)' in 155ms.
2024-05-16 12:44:06.196 [info] [Trace - 12:44:06] Sending notification 'textDocument/didChange'.

```

And my vscode software environment:
```
版本: 1.89.1 (user setup)
提交: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
日期: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621
```

Here is a sample from Jupyterlab:
![image](https://github.com/microsoft/vscode-autopep8/assets/22177897/61bf8614-22b4-4642-b50d-defdef9dee09)


The VS Code and Jupyterlab are on different servers. Jupyterlab runs Python 3.10.13, and VS Code runs python 3.12.3

**Comment by karthiknadig** [comment]
I need to know the version of autopep8. This extension just runs `autopep8` on your behalf. We don’t do anything in particular here. What we do is equivalent to running `type <script path> | python -m autopep8 -` and returning the result.

I was not able to repro this locally, so I am assuming this is because the version of `autopep8` used might be different.

The logs from Output > autopep8 has this info. Please share the full log.

**Comment by mattholy** [comment]
Get it.
But I'm pretty sure it is 2.1.0
![image](https://github.com/microsoft/vscode-autopep8/assets/22177897/b59281f3-6faa-4327-8c98-7f2e3cec751c)

**Comment by mattholy** [comment]
I was mistaken. After investigation, I found that the problem lies with the Python code highlighting plugin, not with autopep8.
