### ISSUE TITLE
Autopep8 2.3

### ISSUE THREAD

**Issue by nmoreaud** [microsoft/vscode-autopep8#294]
Hello

Could you please update the shipped autopep8 to version 2.3.X?
Regards

**Comment by nmoreaud** [comment]
Did you just publish it?
I tried a few hours ago and I still had an inferior version

**Comment by karthiknadig** [comment]
It has been out for a few months:
![Image](https://github.com/user-attachments/assets/5806243b-8961-4421-a5fc-87934662e3ba)

You need to install the pre-release version. see the "switch to pre-release":
![Image](https://github.com/user-attachments/assets/e8e8ed48-4ffb-4103-9be7-0d5daa11df87)

We will publish this to stable soon.

**Comment by eleanorjboyd** [comment]
closing as stale- please comment and ill reopen if thats not the case
