### ISSUE TITLE
Plugin should ignore `--recursive`

### ISSUE THREAD

**Issue by Avasam** [microsoft/vscode-autopep8#32]
Because of the following `pyproject.toml` configuration:
```toml
[tool.autopep8]
recursive = true
```

I get the following autopep8 output:
```
c:\Program Files\Python39\python.exe -m autopep8 --max-line-length=120 -
CWD Server: c:\Users\Avasam\Documents\Git\Auto-Split
--recursive cannot be used with standard input
```

And the formatting fails. This is not an issue with in `ms-python.python`

**Comment by karthiknadig** [comment]
This cannot be directly addressed in the extension, since this is not passed in via args to the extension. I created an issue on `autopep8` to provide a flag to control this: see here https://github.com/hhatto/autopep8/issues/675
