### ISSUE TITLE
Support format on type for `autopep8`

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-autopep8#77]
As the title says, I've tried autopep8 and black. My codes can be formatted after saved however "FormatOnType" didn't work at al.

I searched this function, and I found [an issue](https://github.com/Microsoft/vscode-python/issues/1586) in 2018.

Has this feature been truly implemented? It still doesn't know how to format after multiple line breaks, so I have to manually save the files frequently.

**Comment by karthiknadig** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
