### ISSUE TITLE
The indent the number of spaces is not a multiple of "tabSize"

### ISSUE THREAD

**Issue by Cazs03** [microsoft/vscode-autopep8#88]
The indent color if the number of spaces is not a multiple of "tabSize"
![image](https://user-images.githubusercontent.com/6555389/236742353-df3fed05-ebda-4ef8-aee4-3d81122eb620.png)
Issue relate with another extension indent-rainbow
the last part are space not multiple of tab

**Comment by karthiknadig** [comment]
@Cazs03 We don't really controll how `autopep8` formats things. Try running this from command line and see if the reprodices the same issue. If it does, please file it on https://github.com/hhatto/autopep8/issues
