### ISSUE TITLE
autopep8 formatting doesn't do anything in colorize-fixtures/test.py

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-autopep8#9]
Testing microsoft/vscode-python#19885

Trying to format this, I don't know exactly how it's supposed to look but it seems by formatting the example file in microsoft/vscode-python#19885, there should at least be 2 spaces between classes/defs at the top level? There's zero feedback on format.

https://github.com/microsoft/vscode/blob/d31d71d8cc480313088a384ebb2c9e4f682601ae/extensions/python/test/colorize-fixtures/test.py#L21

![Recording 2022-09-28 at 08 06 44](https://user-images.githubusercontent.com/2193314/192815457-5cb82c3f-11a9-4248-8b2f-0f52ebb8ae1a.gif)

**Comment by karthiknadig** [comment]
This is expected. The code has syntax errors. so it won't be formatted.

**Comment by Tyriar** [comment]
Shouldn't the user be told that it wasn't formatted? Otherwise the feedback is the same for success and failure.

**Comment by Tyriar** [comment]
👍 thanks for clarifying
